<?php
class Pokemon {
	static public function html_index() {
		$resultat = '';
		$resultat .= '<div class="liste">';
		$resultat .= '<h1>Les Pokémons</h1>';
		$resultat .= '<table border="1">';
		$resultat .= '<thead>';
		$resultat .= '<tr>';
		$resultat .= '<th>No</th>';
		$resultat .= '<th>Icône</th>';
		$resultat .= '<th>Nom français</th>';
		$resultat .= '</tr>';
		$resultat .= '</thead>';
		$resultat .= '<tbody>';
		$resultat .= '<tr>';
		$resultat .= '<td>1</td>';
		$resultat .= '<td><img src="https://pokestrat.io/images/badges/1.png" alt="Bulbizarre" style="width:64px; height:64px;"/></td>';
		$resultat .= '<td><a href="details.php?id=1">Bulbizarre</a></td>';
		$resultat .= '</tr>';
		$resultat .= '<tr>';
		$resultat .= '<td>2</td>';
		$resultat .= '<td><img src="https://pokestrat.io/images/badges/2.png" alt="Herbizarre" style="width:64px; height:64px;"/></td>';
		$resultat .= '<td><a href="details.php?id=703">Herbizarre</a></td>';
		$resultat .= '</tr>';
		$resultat .= '</tbody>';
		$resultat .= '</table>';
		$resultat .= '</div>';
		return $resultat;
	}
	static public function html_details($id) {
		$resultat = '';
		$resultat .= '<div class="details">';
		$resultat .= '<h1>Bulbizarre</h1>';
		$resultat .= '<div><img src="https://www.pokebip.com/pokedex-images/artworks/1.png" alt=""></div>';
		$resultat .= '</div>';
		$resultat .= '<div class="infos">';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Numéro</span>';
		$resultat .= '<span class="valeur">001</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Nom français</span>';
		$resultat .= '<span class="valeur">Bulbizarre</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Nom anglais</span>';
		$resultat .= '<span class="valeur">Bulbasaur</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Type(s)</span>';
		$resultat .= '<span class="valeur">plante/poison</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Talents</span>';
		$resultat .= '<span class="valeur">Engrais/Chlorophylle</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Points de vie</span>';
		$resultat .= '<span class="valeur">45</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Attaque</span>';
		$resultat .= '<span class="valeur">49</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Défense</span>';
		$resultat .= '<span class="valeur">49</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Attaque spéciale</span>';
		$resultat .= '<span class="valeur">65</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Défense spéciale</span>';
		$resultat .= '<span class="valeur">65</span>';
		$resultat .= '</div>';
		$resultat .= '<div class="donnee">';
		$resultat .= '<span class="etiquette">Vitesse</span>';
		$resultat .= '<span class="valeur">45</span>';
		$resultat .= '</div>';
		$resultat .= '</div>';			
		return $resultat;
	}
}